
# Homework 1: "P8105_hw1_jw3597"
#### Name: Jessie Wong 
#### Date: Sept 16, 2018

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### Problem 1 
```{r}
## A random sample of size 10 from a uniform [0,5] distribution
x = runif(10, min = 0, max = 5)
x
  
## A logical vector indicating whether elements of the sample are greater than 2
x > 2

## A (length-10) character vector
food <- c("I", "am", "very", "hungry", "would", "you", "like", "to", "go", "eat")

## A (length-10) factor vector
size <- c("Small", "Large", "Medium", "Medium", "Medium", "Large", "Small", "Large", "Large", "Medium")

## Creating a data frame comprised of the variables above
homework_df = tibble(
  vec_char = c("I", "am", "very", "hungry", "would", "you", "like", "to", "go", "eat"),
  vec_logical = c(x > 2),
  vec_factor = factor(c("Small", "Large", "Medium", "Medium", "Medium", "Large", "Small", "Large", "Large", "Medium"))
)

homework_df
```


```{r}
## Mean of logical vector 
mean(x > 2)

## Mean of character vector
mean(food)

## Mean of factor vector
mean(size)

## Out of the 3 variables, only the logical vector was able to produce a mean (0.6). It did not work for character and factor vector because both are not numeric or logical. 
```

```{r}
## Applying as.numeric function to logical, character, and factor variables
as.numeric(as.factor(size))

as.numeric(as.character(food))

as.numeric(as.logical(x > 2))
```

```{r}
## Converting character variable from character to factor to numeric
as.numeric(as.factor(food))

## Converting factor variable from factor to character to numeric
as.numeric(as.character(size))

## When I tried to convert character variable from character to factor to numeric, I was able to make the conversion and the output was numeric. However, when I tried converting factor variable from factor to character to numeric, the output was all NA.
```

### Problem 2
```{r}
## Creating a data frame 
plot_df = tibble(
  x = rnorm(1000),
  y = rnorm(1000),
  sum = x + y > 0,
  sum1 = as.numeric(sum),
  sum2 = as.factor(sum)
)

plot_df

```

Short description of the vector above: 
The size of the data set is `r nrow(plot_df)` rows and `r ncol(plot_df)` columns. The mean is `r mean(x)`. The proportion of cases for which the logical vector is TRUE is `r sum(plot_df$sum == TRUE)/nrow(plot_df)`.

```{r}
## Scatterplot of y vs x (using the logical variable)
ggplot(plot_df, aes(x = x, y = y)) + geom_point(aes(color = sum))

## Scatterplot of y vs x (using the numeric variable)
ggplot(plot_df, aes(x = x, y = y)) + geom_point(aes(color = sum1))

## Scatterplot of y vs x (using the factor variable)
ggplot(plot_df, aes(x = x, y = y)) + geom_point(aes(color = sum2))

## The color scale for the first scatterplot using logical variable and the third scatterplot using factor variable consisted of two contrasting colors (red and blue) representing "true" or "false". The color scale for the second scatterplot using numeric variable, consisted of a blue gradient corresponding to values from 0.00 to 1.00.  
```

```{r}
## Export first scatterplot to project directory using ggsave
ggplot(plot_df, aes(x = x, y = y)) + geom_point(aes(color = sum))
ggsave("scatter_plot1.pdf", height = 4, width = 6)
```
